baseURL = "https://www.karinacrisp.com/"
languageCode = "en-us"
summaryLength = 30
[[menu.main]]
name = "Home Value Request"
parent = "Buyers & Sellers"
url = "https://karinacrisp.netlify.app/home-value-request/"
weight = 3
[[menu.main]]
name = "Advanced Search"
parent = "Property Search"
url = "https://karinacrisp.idxhome.com/listing/search/advanced/147919/306?location=&propertyType=SFR%2CCND&minListPrice=&maxListPrice=&squareFeet=&bedrooms=0&bathCount=0&_openHomesOnlyYn=on&_dateRange=on&_virtualTourYn=on"
weight = 2
[[menu.main]]
name = "Mortgage Calculator"
parent = "Buyers & Sellers"
url = "https://karinacrisp.idxhome.com/mortcalc/147919"
weight = 2
[[menu.main]]
name = "Search"
parent = "Property Search"
url = "https://karinacrisp.idxhome.com/homesearch/147919"
weight = 1
[[menu.main]]
name = "Property Organizer"
parent = "Buyers & Sellers"
url = "https://karinacrisp.idxhome.com/organizer/login/147919"
weight = 1
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[[menu.main]]
name = "Featured Listings"
url = "https://karinacrisp.idxhome.com/featured/147919"
weight = 2
[[menu.main]]
name = "Buyers & Sellers"
weight = 4
[[menu.main]]
name = "Property Search"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
