baseURL = "https://www.karinacrisp.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 30
[[menu.main]]
name = "Home"
url = "https://www.karinacrisp.com"
weight = 1
[[menu.main]]
name = "Search Homes"
weight = 2
[[menu.main]]
name = "Buyers & Sellers"
url = "https://search.karinacrisp.com/organizer/login/147919"
weight = 3
[[menu.main]]
name = "My Account"
url = "https://search.karinacrisp.com/organizer/login/147919"
weight = 4
[[menu.main]]
name = "Contact"
url = "https://www.karinacrisp.com/contact"
weight = 5
[[menu.main]]
name = "Home Value Request"
parent = "Buyers & Sellers"
url = "https://www.karinacrisp.com/home-value-request"
weight = 1
[[menu.main]]
name = "Mortgage Calculator"
parent = "Buyers & Sellers"
url = "https://search.karinacrisp.com/mortcalc/147919"
weight = 2
[[menu.main]]
name = "Featured Listings"
parent = "Search Homes"
url = "https://search.karinacrisp.com/featured/147919"
weight = 3
[[menu.main]]
name = "Basic Search"
parent = "Search Homes"
url = "https://search.karinacrisp.com/homesearch/147919"
weight = 1
[[menu.main]]
name = "Advanced Search"
parent = "Search Homes"
url = "https://search.karinacrisp.com/listing/search/advanced/147919/74?location=Enter+cities+or+zip+codes&propertyType=SFR%2CCND&minListPrice=&maxListPrice=&squareFeet=&bedrooms=0&bathCount=0&_openHomesOnlyYn=on&_dateRange=on&_virtualTourYn=on"
weight = 2
