---
label: IDX Config
hide_body: true
fields:
- name: enable_idx
  type: boolean
  label: Enable IDX
- name: ihomefinder_client_id
  type: number
  label: Ihomefinder Client ID
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: subdomain
  type: text
  config:
    required: false
  label: Subdomain
pages:
- data/idx.yaml
